name: GitHub Actions Demo
on: [push]
jobs:
  before:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v

  test:
    runs-on: ubuntu-latest
    steps:
      - run: npm -v
